name: 'Persist GitHub Issues to Files'
description: 'Bidirectional sync between GitHub Issues and markdown files'
author: 'nsheaps'

inputs:
  mode:
    description: 'Mode: scan-todos or sync-issues'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  repository:
    description: 'Repository in owner/name format'
    required: false
    default: ${{ github.repository }}
  event-type:
    description: 'Event type: push, pull_request, or issues'
    required: false
    default: 'push'
  changed-files:
    description: 'Newline-separated list of changed files'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}/../..
        npm install --include=dev
    
    - name: Run TODO scanner
      if: inputs.mode == 'scan-todos'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        npx tsx ${{ github.action_path }}/src/scan-todos/index.ts
    
    - name: Run issue sync
      if: inputs.mode == 'sync-issues'
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        EVENT_TYPE: ${{ inputs.event-type }}
        CHANGED_FILES: ${{ inputs.changed-files }}
      run: |
        npx tsx ${{ github.action_path }}/src/sync-issues/index.ts
